// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Data;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260901012730_InitialVehiculosSchema")]
    partial class InitialVehiculosSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Model.Marca", b =>
                {
                    b.Property<long>("MarcaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MarcaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MarcaId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre");

                    b.HasKey("MarcaId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Marcas", "dbo");
                });

            modelBuilder.Entity("Domain.Model.Vehiculo", b =>
                {
                    b.Property<long>("VehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("VehiculoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("VehiculoId"));

                    b.Property<int>("Anio")
                        .HasColumnType("int")
                        .HasColumnName("Anio");

                    b.Property<int>("CantidadPuertas")
                        .HasColumnType("int")
                        .HasColumnName("CantidadPuertas");

                    b.Property<long>("MarcaId")
                        .HasColumnType("bigint")
                        .HasColumnName("MarcaID");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Modelo");

                    b.HasKey("VehiculoId");

                    b.HasIndex("MarcaId")
                        .HasDatabaseName("IX_Vehiculos_Marca");

                    b.ToTable("Vehiculos", "dbo");
                });

            modelBuilder.Entity("Domain.Model.Venta", b =>
                {
                    b.Property<long>("VentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("VentaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("VentaId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("Cantidad");

                    b.Property<double>("TotalVenta")
                        .HasColumnType("float")
                        .HasColumnName("TotalVenta");

                    b.Property<long>("VehiculoId")
                        .HasColumnType("bigint")
                        .HasColumnName("VehiculoID");

                    b.HasKey("VentaId");

                    b.HasIndex("VehiculoId")
                        .IsUnique()
                        .HasDatabaseName("IX_Ventas_Vehiculo");

                    b.ToTable("Ventas", "dbo");
                });

            modelBuilder.Entity("Domain.Model.Vehiculo", b =>
                {
                    b.HasOne("Domain.Model.Marca", "Marca")
                        .WithMany("Vehiculos")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("Domain.Model.Venta", b =>
                {
                    b.HasOne("Domain.Model.Vehiculo", "Vehiculo")
                        .WithOne("Venta")
                        .HasForeignKey("Domain.Model.Venta", "VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Domain.Model.Marca", b =>
                {
                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("Domain.Model.Vehiculo", b =>
                {
                    b.Navigation("Venta");
                });
#pragma warning restore 612, 618
        }
    }
}
